### ISSUE TITLE
Make Perrin not dead.

### ISSUE THREAD

**Issue by Abigail** [rjbs/RPG-Beyond#16]
Perrin is dead.

He should become not dead.

A few leads:

- Frank says, there's a machine on level 6 of Foxhole we can ask.
- Rago suggests to asks the goblins on level 4.
- Harald, Beeta, Kim suggest killing the heretic, and using its vine. But they all think it's a bad idea.
- Beeta suggests the elves (in the forest we crossed after fleeing Edgewold)
- The magical house (where the party went to to get Perrins leg repaired)
- Go to a farm, and wait for the right person to stop by
- Sign him up for the empire's "dead squad".

Also, "the empire" has contacted dead-Perrin, but obviously, the rest of the party is unaware.

Failing all that, we may sell his body to the dam building zombies.

**Comment by wolfsage** [comment]
PERRIN IS NOT DEAD. Revived by Haslan Gladwell.
