### ISSUE TITLE
Skin the dead wolves.

### ISSUE THREAD

**Issue by Abigail** [rjbs/RPG-Beyond#18]
We brought three dead wolves back to Foxholes. If we can't skin and cure their hides ourselves, we may want to find someone who does it for us. Or else, sell the corpses to someone who sees the value in them.

**Comment by Abigail** [comment]
Perrin is working on this.

**Comment by wolfsage** [comment]
We started this apparently:

````
Perrin tans some hides (the dead wolves)

There's metal fibre going through their bodies. Especially in their heads.

(Not blue).

Growing around their bones. Thin black wire. Almost like spider silk.

Perrin doesn't feel like the meat is too riddled with metal fibres. Might
be a few in there like little fish bones.
````

**Comment by rjbs** [comment]
Perrin will add this to his inventory.

**Comment by wolfsage** [comment]
Done!
