### ISSUE TITLE
Box in a tree west of Foxhole

### ISSUE THREAD

**Issue by rjbs** [rjbs/RPG-Beyond#2]
Perrin and Knash found a wooden box with a metal cube inside it, with a metal cylinder inside that, in a tree, near three ruined houses with acid zombies in them.

**Comment by wolfsage** [comment]
There's 3 old cabins (well 2 now, we burned one down).

In two of them there were acid-ooze-monster-people thingies (1 per cabin). We killed them.

There was a sign of a third in the other cabin but we never saw them. Dunno if they are dead or wandering around.

In the center of the clearing where the 3 cabins are is a well.

One of the ooze zombies was *really really* interested in getting to that well.

Perrin saw a pseudopod peek out of the well at one point then disappear back down it (!)

**Comment by Abigail** [comment]
The party burned one of the cabins (but we didn't resolve whether the cabin was burned to the ground, or whether it's still partially standing)

**Comment by wolfsage** [comment]
Box acquired! See #13
