### ISSUE TITLE
Revisit the cave?

### ISSUE THREAD

**Issue by rjbs** [rjbs/RPG-Beyond#5]
There was talk of going back to the cave where Perrin and Knash's lost time began.

**Comment by Abigail** [comment]
Yes, but then certain people first wanted to retrieve their camel, so we got side tracked.

**Comment by wolfsage** [comment]
OFF WE GO

**Comment by Abigail** [comment]
Found it, and got our stuff.

Hopefully, we bring it safely back.

**Comment by wolfsage** [comment]
Done and done
